name: course_travel
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  d_method: ^0.2.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  extended_image: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.18.1
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
